### ISSUE TITLE
Multi Agent Environment Needs Fixing 

### ISSUE THREAD

**Issue by CuriousBeluga** [tabathaviso/UAV-swarm-path-planning#1]
Single UAV works, issue is that multiple agent sim throws errors:

- A* might be getting confused
- Or path might not be clearly returned
- Need to add some kind of test to see what is actually happening 

If Multi-agent sim doesn't work by EOD 7/2/23, transition to single UAV sim for phase 2 progress report

**Comment by tabathaviso** [comment]
Wyatt made significant improvements to the multi-agent sim.
However, some issues still need to be addressed, swarm algorithm needs to define final "best" path.
Also, we should re-consider swarm initialization points -> randomization?
